spring:
  application:
    name: finance-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/FinanceTracker
    username: postgres
    password: Kru@123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

app:
  jwt:
    secret: <SECRET_KEY_CHANGE_ME_FOR_PRODUCTION_32_BYTES_MINIMUM>
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 604800000

logging:
  level:
    com.financetracker: INFO
    org.springframework.security: INFO
